// Code generated by Slice Machine. DO NOT EDIT.

import AboutMe from './AboutMe/index.svelte';
import Chat from './Chat/index.svelte';
import Footer from './Footer/index.svelte';
import Header from './Header/index.svelte';
import Introduction from './Introduction/index.svelte';
import SocialMedia from './SocialMedia/index.svelte';

export const components = {
	about_me: AboutMe,
	chat: Chat,
	footer: Footer,
	header: Header,
	introduction: Introduction,
	social_media: SocialMedia
};
