// Code generated by Slice Machine. DO NOT EDIT.

import Chat from './Chat/index.svelte';
import Introduction from './Introduction/index.svelte';
import Header from './Header/index.svelte';

export const components = {
	chat: Chat,
	introduction: Introduction,
	rich_text: Header
};
