// Code generated by Slice Machine. DO NOT EDIT.

import Introduction from './Introduction/index.svelte';
import Header from './Header/index.svelte';

export const components = {
	introduction: Introduction,
	rich_text: Header
};
