// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
	| RichTextSlice
	| IntroductionSlice
	| ChatSlice
	| AboutMeSlice
	| SocialMediaSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
	/**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *AboutMe → Primary*
 */
export interface AboutMeSliceDefaultPrimary {
	/**
	 * about_me_title field in *AboutMe → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_me.primary.about_me_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	about_me_title: prismic.RichTextField;

	/**
	 * about_me_intro field in *AboutMe → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_me.primary.about_me_intro
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	about_me_intro: prismic.RichTextField;

	/**
	 * about_me_likes field in *AboutMe → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_me.primary.about_me_likes
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	about_me_likes: prismic.RichTextField;

	/**
	 * about_me_dislikes field in *AboutMe → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_me.primary.about_me_dislikes
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	about_me_dislikes: prismic.RichTextField;
}

/**
 * Default variation for AboutMe Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AboutMeSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *AboutMe*
 */
type AboutMeSliceVariation = AboutMeSliceDefault;

/**
 * AboutMe Shared Slice
 *
 * - **API ID**: `about_me`
 * - **Description**: AboutMe
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSlice = prismic.SharedSlice<'about_me', AboutMeSliceVariation>;

/**
 * Primary content in *Chat → Primary*
 */
export interface ChatSliceDefaultPrimary {
	/**
	 * chat_title field in *Chat → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: chat.primary.chat_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	chat_title: prismic.RichTextField;
}

/**
 * Default variation for Chat Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChatSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ChatSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Chat*
 */
type ChatSliceVariation = ChatSliceDefault;

/**
 * Chat Shared Slice
 *
 * - **API ID**: `chat`
 * - **Description**: Chat
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ChatSlice = prismic.SharedSlice<'chat', ChatSliceVariation>;

/**
 * Primary content in *Introduction → Primary*
 */
export interface IntroductionSliceDefaultPrimary {
	/**
	 * introduction_title field in *Introduction → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: introduction.primary.introduction_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	introduction_title: prismic.RichTextField;

	/**
	 * introduction_bio field in *Introduction → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: introduction.primary.introduction_bio
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	introduction_bio: prismic.RichTextField;

	/**
	 * introduction_image field in *Introduction → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: introduction.primary.introduction_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	introduction_image: prismic.ImageField<never>;
}

/**
 * Default variation for Introduction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<IntroductionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Introduction*
 */
type IntroductionSliceVariation = IntroductionSliceDefault;

/**
 * Introduction Shared Slice
 *
 * - **API ID**: `introduction`
 * - **Description**: Introduction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSlice = prismic.SharedSlice<'introduction', IntroductionSliceVariation>;

/**
 * Primary content in *Header → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * header_profile_image field in *Header → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.header_profile_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	header_profile_image: prismic.ImageField<never>;

	/**
	 * header_profile_name field in *Header → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.header_profile_name
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	header_profile_name: prismic.RichTextField;

	/**
	 * header_social_button field in *Header → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.primary.header_social_button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	header_social_button: prismic.LinkField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Header*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

/**
 * Primary content in *SocialMedia → Primary*
 */
export interface SocialMediaSliceDefaultPrimary {
	/**
	 * social_media_title field in *SocialMedia → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_media.primary.social_media_title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	social_media_title: prismic.RichTextField;

	/**
	 * social_media_option1 field in *SocialMedia → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_media.primary.social_media_option1
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	social_media_option1: prismic.LinkField;

	/**
	 * social_media_option2 field in *SocialMedia → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_media.primary.social_media_option2
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	social_media_option2: prismic.LinkField;

	/**
	 * social_media_option3 field in *SocialMedia → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_media.primary.social_media_option3
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	social_media_option3: prismic.LinkField;
}

/**
 * Default variation for SocialMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SocialMediaSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *SocialMedia*
 */
type SocialMediaSliceVariation = SocialMediaSliceDefault;

/**
 * SocialMedia Shared Slice
 *
 * - **API ID**: `social_media`
 * - **Description**: SocialMedia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialMediaSlice = prismic.SharedSlice<'social_media', SocialMediaSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AboutMeSlice,
			AboutMeSliceDefaultPrimary,
			AboutMeSliceVariation,
			AboutMeSliceDefault,
			ChatSlice,
			ChatSliceDefaultPrimary,
			ChatSliceVariation,
			ChatSliceDefault,
			IntroductionSlice,
			IntroductionSliceDefaultPrimary,
			IntroductionSliceVariation,
			IntroductionSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault,
			SocialMediaSlice,
			SocialMediaSliceDefaultPrimary,
			SocialMediaSliceVariation,
			SocialMediaSliceDefault
		};
	}
}
